/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasinilai;
import aplikasinilai.Koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;  
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author asus
 */
public class formmahasiswa extends javax.swing.JFrame {
    private String sql;
    private PreparedStatement ps=null;
    public String tanggal;
    
    public formmahasiswa() {
       initComponents();
       tampilanData ();
    }
    private void tampilanData(){
    try {
      String sql="SELECT * FROM tb_mahasiswa";
      PreparedStatement ps=null;
      Object [] row={"NIM","Nama Mahasiswa","Tempat lahir","Tanggal Lahir"
              ,"jenis kelamin", "Alamat"};
      DefaultTableModel dtm=new DefaultTableModel (null,row);
      tabelmhs.setModel (dtm);
      jScrollPane1.setEnabled(true);
      jScrollPane1.setBorder(null);
      jScrollPane1.setViewportView(tabelmhs);
    ResultSet rs=null;
        ps=Koneksi.KoneksiDatabase().prepareStatement(sql);
        rs=ps.executeQuery();
        while(rs.next()){
            String nim=rs.getString(1);
            String namamahasiswa=rs.getString(2);
            String tempatlahir=rs.getString(3);
            String tgllahir=rs.getString(4);
            String jeniskelamin=rs.getString(5);
            String alamat=rs.getString(6);
            String [] baris={nim,namamahasiswa,tempatlahir,tgllahir,jeniskelamin,alamat};
            dtm.addRow(baris);
        }
        }catch(Exception e){}
    }
    
    private void bersih(){
        txtnim.setText("");
        txtnamamhs.setText("");
        txttempatlahir.setText("");
        txtalamat.setText("");
    }
       
    private void simpan() throws SQLException{
        try{
            if((txtnim.getText().equals(""))
              ||((txtnamamhs.getText().equals(""))
              ||(txttempatlahir.getText().equals(""))
              ||(cmbjk.getSelectedItem().equals("-Pilih Jenis Kelamin-"))
              ||(txtalamat.getText().equals(""))))
            {
                JOptionPane.showMessageDialog(rootPane,"Lengkapi Data dengan benar !");
            }
            else
            {
                String sqlA="select*from tb_mahasiswa where nim='"+txtnim.getText()+"'";
                ps=Koneksi.KoneksiDatabase().prepareStatement(sqlA);
                ResultSet rs=ps.executeQuery(sqlA);
                System.out.println(rs.first());
                if(rs.first()==true)
                {
                    JOptionPane.showMessageDialog(rootPane,"Data Sudah Ada!");
                }
                else
                {
                    String sqlB="insert into tb_mahasiswa(nim,nama_mahasiswa,tempat_lahir,tgl_lahir,jk,alamat)values"+
                    "('"+txtnim.getText()+
                    "','"+txtnamamhs.getText()+
                    "','"+txttempatlahir.getText()+
                    "','"+tanggal+
                    "','"+cmbjk.getSelectedItem()+
                    "','"+txtalamat.getText()+"')";
                   ps=Koneksi.KoneksiDatabase().prepareStatement(sqlB);
                   ps.executeUpdate(sqlB);
                   JOptionPane.showMessageDialog(rootPane,"Data berhasil di simpan!");
                   tampilanData();
                   bersih();
                }  
            }
            }catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(rootPane,"Cek lagi sistem!"+e.getMessage());
                    }
        }
    
    private void ambildatadaritabel(){
        int row = tb_mahasiswa.getSelectedRow();
        txtnim.setText(tb_mahasiswa.getModel().getValueAt(row,0).toString());
        txtnamamhs.setText(tb_mahasiswa.getModel().getValueAt(row,1).toString());
        txttemplhr.setText(tb_mahasiswa.getModel().getValueAt(row,2).toString());
    }
    //khusus untuk tanggal
    String tgl =(String) tb_mahasiswa.getModel().getValueAt(row,3);
    
    try{
       SimpleDateFormat format= new SimpleDateFormat("yyyy-MM-dd");
       java.util.Date d = format.parse(tgl);
       cldtgl
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        txtnim = new javax.swing.JTextField();
        txtnamamhs = new javax.swing.JTextField();
        txttempatlahir = new javax.swing.JTextField();
        calendertgllahir = new com.toedter.calendar.JCalendar();
        cmbjk = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmhs = new javax.swing.JTable();
        btnkeluar = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Form Input Data Mahasiswa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Form Input Data Mahasiswa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nama Mahasiswa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tempat Lahir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tempat Lahir");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal lahir ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Jenis kelamin");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 270, -1));

        txtnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnimActionPerformed(evt);
            }
        });
        getContentPane().add(txtnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 100, -1));
        getContentPane().add(txtnamamhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 270, -1));
        getContentPane().add(txttempatlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 150, -1));

        calendertgllahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendertgllahirPropertyChange(evt);
            }
        });
        getContentPane().add(calendertgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 230, -1));

        cmbjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih jenis kelamin--", "Laki-laki", "Perempuan" }));
        getContentPane().add(cmbjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        tabelmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelmhs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 650, -1));

        btnkeluar.setText("keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        btnsimpan.setText("simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        btnedit.setText("edit");
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        btnhapus.setText("hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnimActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
    bersih();        
// TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        try {
            // TODO add your handling code here:
            simpan();
        } catch (SQLException ex) {
            Logger.getLogger(formmahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void calendertgllahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendertgllahirPropertyChange
        // TODO add your handling code here:
        try{
       if(calendertgllahir.getDate()!=null){
          String ubahtanggal ="yyyy/MM/dd";
          SimpleDateFormat format=new SimpleDateFormat(ubahtanggal);
          tanggal=String.valueOf(format.format(calendertgllahir.getDate()));
         }
       }catch(Exception e){

       }
    }//GEN-LAST:event_calendertgllahirPropertyChange

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
    dispose();        
// TODO add your handling code here:
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formmahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private com.toedter.calendar.JCalendar calendertgllahir;
    private javax.swing.JComboBox<String> cmbjk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelmhs;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnamamhs;
    private javax.swing.JTextField txtnim;
    private javax.swing.JTextField txttempatlahir;
    // End of variables declaration//GEN-END:variables
}
